<?php
/* $Id$ */
// vim:set ft=php:

/**
 * @file
 * GMap Taxonomy Markers
 *
 * Taxonomy based markers.
 */

/**
 * Implementation of hook_form_alter().
 */
function gmap_taxonomy_form_alter($form_id, &$form) {
  if ($form_id == 'taxonomy_form_vocabulary') {
    $form['gmap_taxonomy'] = array(
      '#type' => 'fieldset',
      '#title' => t('GMap markers'),
    );
    $vid = isset($form['vid']) ? $form['vid']['#value'] : -1;
    $temp = variable_get('gmap_taxonomy_vocabs', array());
    if (!isset($temp[$vid])) {
      $temp[$vid] = 0;
    }
    $form['gmap_taxonomy']['gmap_taxonomy_enable'] = array(
      '#type' => 'checkbox',
      '#title' => t('Enable'),
      '#description' => t('Enable choosing a marker for terms in this vocabulary.'),
      '#default_value' => $temp[$vid],
    );
    $form['submit']['#weight']++;
    if ($form['delete']) {
      $form['delete']['#weight']+=2;
    }
  }
  if ($form_id == 'taxonomy_form_term') {
    $vid = $form['vid']['#value'];
    $vocs = variable_get('gmap_taxonomy_vocabs', array());
    if (isset($vocs[$vid]) && $vocs[$vid]) {
      $temp = '';
      if (isset($form['tid'])) {
        if ($t = db_result(db_query('SELECT marker FROM {gmap_taxonomy_term} WHERE tid = %d', $form['tid']['#value']))) {
          $temp = $t;
        }
      }
      $form['gmap_taxonomy_marker'] = array(
        '#title' => t('GMap Marker'),
        '#type' => 'select',
        '#options' => array('' => '') + gmap_get_marker_titles(),
        '#description' => t('If you would like nodes tagged as this term to have a special marker, choose one here.'),
        '#default_value' => $temp,
      );
      $form['submit']['#weight']++;
      if ($form['delete']) {
        $form['delete']['#weight']+=2;
      }
    }
  }
}

/**
 * Implementation of hook_taxonomy().
 */
function gmap_taxonomy_taxonomy($op, $type, $array = NULL) {
  if ($type == 'vocabulary') {
    switch ($op) {
      case 'insert':
      case 'update':
        $status = variable_get('gmap_taxonomy_vocabs', array());
        $status[$array['vid']] = $array['gmap_taxonomy_enable'];
        variable_set('gmap_taxonomy_vocabs', $status);
        break;
      case 'delete':
        $status = variable_get('gmap_taxonomy_vocabs', array());
        unset($status[$array['vid']]);
        variable_set('gmap_taxonomy_vocabs', $status);
    }
  }
  else {
    switch ($op) {
      case 'insert':
      case 'update':
        if (isset($array['gmap_taxonomy_marker']) && !empty($array['gmap_taxonomy_marker'])) {
          db_query('DELETE FROM {gmap_taxonomy_term} WHERE tid = %d', $array['tid']);
          db_query("INSERT INTO {gmap_taxonomy_term} (tid, marker) VALUES (%d, '%s')", $array['tid'], $array['gmap_taxonomy_marker']);
        }
        break;
      case 'delete':
        db_query('DELETE FROM {gmap_taxonomy_term} WHERE tid = %d', $array['tid']);
    }
  }
}

/**
 * Implementation of hook_nodeapi().
 */
function gmap_taxonomy_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch($op) {
    case 'insert':
    case 'update':
      $status = variable_get('gmap_taxonomy_vocabs', array());
      $marker = '';
      foreach ($node->taxonomy as $voc => $terms) {
        if (isset($status[$voc]) && $status[$voc]) {
          $t = $terms;
          if (!is_array($t)) {
            $t = array($t);
          }
          foreach ($t as $term) {
            $m = db_result(db_query('SELECT marker FROM {gmap_taxonomy_term} WHERE tid = %d', $term));
            if (!empty($m)) {
              $marker = $m;
            }
          }
        }
      }
      if (!empty($marker)) {
        db_query('DELETE FROM {gmap_taxonomy_node} WHERE vid = %d', $node->vid);
        db_query("INSERT INTO {gmap_taxonomy_node} (nid, vid, marker) VALUES (%d, %d, '%s')", $node->nid, $node->vid, $marker);
      }
      break;

    case 'delete':
      db_query('DELETE FROM {gmap_taxonomy_node} WHERE nid = %d', $node->nid);
      break;
    case 'delete revision':
      db_query('DELETE FROM {gmap_taxonomy_node} WHERE vid = %d', $node->vid);
      break;
  }
}

/**
 * Implementation of hook_views_tables().
 */
function gmap_taxonomy_views_tables() {
  $tables['gmap_taxonomy_node'] = array(
    'fields' => array(
      'marker' => array(
        'name' => t('GMap Taxonomy: Marker'),
        'help' => t('Displays the marker name GMap Taxonomy associates with this node.'),
      ),
    ),

    'join' => array(
      'left' => array(
        'table' => 'node',
        'field' => 'vid',
      ),
      'right' => array(
        'field' => 'vid',
      ),
    ),
  );
  return $tables;
}