<?php
// $Id$

/**
 * @file
 *  GMap install file
 */

/**
 * Implementation of hook_uninstall().
 */
function gmap_uninstall() {
  variable_del('gmap_method');
  variable_del('gmap_wms');
  variable_del('gmap_default');
  variable_del('gmap_mm_type');
  variable_del('gmap_load_zoom_plugin');
  variable_del('gmap_markermanager');
  variable_del('gmap_markerfiles');
  variable_del('gmap_location_map');
  variable_del('gmap_node_markers');

  variable_del('googlemap_api_key');
}
