<?php
/* $Id$ */
// vim:set ft=php:

/**
 * @file
 * GMap Macro Builder
 *
 * A dynamic interface to assist in the creation of gmap macro tags.
 */

/**
 * Implemenation of hook_help().
 */
function gmap_macro_builder_help($section) {
  switch ($section) {
    case 'map/macro':
      return t('You can use this interface to create a map macro suitable for pasting into a node or any other place that accepts a GMap macro.');
  }
}

/**
 * Implementation of hook_perm().
 */
function gmap_macro_builder_perm() {
  return array('create macro');
}

/**
 * Implementation of hook_menu().
 */
function gmap_macro_builder_menu($may_cache) {
  if ($may_cache) {
    $items = array();
    $items[] = array(
      'path' => 'map/macro',
      'type' => MENU_NORMAL_ITEM,
      'title' => t('Build a GMap macro'),
      'access' => user_access('create macro'),
      'callback' => 'drupal_get_form',
      'callback arguments' => 'gmap_macro_builder_form',
    );
    return $items;
  }
}

/**
 * Macro builder form.
 */
function gmap_macro_builder_form() {
  $form['macroform'] = array(
    '#type' => 'fieldset',
    '#title' => t('Gmap macro creation'),
    '#theme' => 'gmap_macro',
  );

  $form['macroform']['mapdiv'] = array(
    '#type' => 'gmap',
    '#map' => 'macro_map',
    '#settings' => array(
      'points' => array(),
      'pointsOverlays' => array(),
      'behavior' => array(
        'dynmarkers' => TRUE,
      ),
    ),
  );

  $defaults = gmap_defaults();

  $form['macroform']['overlayedit'] = array(
    '#type' => 'gmap_overlay_edit',
    '#map' => 'macro_map',
  );
  $form['macroform']['mapid'] = array(
    '#type' => 'textfield',
    '#title' => t('Map id attribute'),
    '#default_value' => variable_get('gmap_default_mapid', 'map'),
  );
  gmap_widget_setup($form['macroform']['mapid'],'mapid','macro_map');

  $form['macroform']['maptype'] = array(
    '#type' => 'select', 
    '#title' => t('Map type'), 
    '#options' => drupal_map_assoc(array('Map', 'Satellite', 'Hybrid')), 
    '#default_value' => $defaults['maptype'],
    '#required' => FALSE,
  );
  gmap_widget_setup($form['macroform']['maptype'],'maptype','macro_map');

  $form['macroform']['controltype'] = array(
    '#type' => 'select', 
    '#title' => t('Controls'), 
    '#options' => drupal_map_assoc(array('None', 'Small', 'Large')), 
    '#required' => FALSE,
    '#default_value' => $defaults['controltype'],
  );
  gmap_widget_setup($form['macroform']['controltype'],'controltype','macro_map');

  $form['macroform']['address'] = array(
    '#type' => 'gmap_address',
    '#map' => 'macro_map',
    '#title' => t('Address'),
    '#default_value' => '',
  );
  $form['macroform']['latlong'] = array(
    '#type' => 'gmap_latlon',
    '#map' => 'macro_map',
    '#title' => t('The Latitude and Longitude of the centre of the map'),
    '#default_value' => $defaults['latlong'],
    '#size' => 50,
  );
  $form['macroform']['width'] = array(
    '#type' => 'textfield',
    '#title' => t('Map width'),
    '#default_value' => $defaults['width'],
    '#size' => 25,
  );
  gmap_widget_setup($form['macroform']['width'],'width','macro_map');

  $form['macroform']['height'] = array(
    '#type' => 'textfield',
    '#id' => 'gmap-map-height0',
    '#title' => t('Map height'),
    '#default_value' => $defaults['height'],
    '#size' => 25,
    '#attributes' => array('class' => 'gmap-control'),
  );
  gmap_widget_setup($form['macroform']['height'],'height','macro_map');

  $form['macroform']['alignment'] = array(
    '#type' => 'gmap_align',
    '#map' => 'macro_map',
    '#title' => t('Alignment'),
  );

  $form['macroform']['zoom'] = array(
    '#type' => 'select',
    '#title' => t('The current magnification of the map'),
    '#default_value' => $defaults['zoom'],
    '#options' => drupal_map_assoc(range(0, 17)),
  );
  gmap_widget_setup($form['macroform']['zoom'],'zoom','macro_map');

  $form['macroform']['macro'] = array(
    '#type' => 'gmap_macrotext',
    '#map' => 'macro_map',
    '#default_value' => '',
    '#title' => t('Macro text'),
  );
  return $form;
}
